nodeLinker: node-modules

plugins:
  - checksum: 4d77204ecc396a20b7fc16e530b680ad1c68984cb5bd985d4443dc9fe4275f83
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.53.1/yarn-plugin"
