app:
  baseUrl: ${APP_BASE_URL}

backend:
  baseUrl: ${APP_BASE_URL}
  listen: ':7007'

  csp:
    connect-src: ["'self'", 'http:', 'https:']
    script-src:
      ["'self'", 'http:', 'https:', "'unsafe-eval'", '${APP_BASE_URL}']
    img-src: ["'self'", 'http:', 'https:', 'data:']

  cors:
    origin: ${APP_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

auth:
  environment: production
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName
catalog:
  # Overrides the default list locations from app-config.yaml as these contain example data.
  # See https://backstage.io/docs/features/software-catalog/#adding-components-to-the-catalog for more details
  # on how to get entities into the catalog.
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
    - type: file
      target: ../../examples/org.yaml
    - type: file
      target: ../../examples/all.yaml
    - type: file
      target: ../../examples/acme-corp.yaml
    - type: file
      target: ../../default-catalog/organisations.yaml
    - type: file
      target: ../../default-catalog/groups.yaml
    - type: file
      target: ../../default-catalog/users.yaml

plausible:
  enabled: true
  dataDomain: ${PLAUSIBLE_DATA_DOMAIN}
  sourceUrl: ${PLAUSIBLE_SOURCE_URL}
