services:
  backstage:
    image: ghcr.io/echohello-dev/backstage:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7007:7007
    # env_file:
    #   - .env
    #   - .env.secrets
