services:
  backstage:
    image: ghcr.io/echohello-dev/backstage:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7007:7007
    volumes:
      - ./app-config.production.yaml:/app/app-config.production.yaml
      - ./app-config.yaml:/app/app-config.yaml
    # env_file:
    #   - .env
