apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-pull-request-docs
  title: GitHub Pull Request Docs
  description: |
    This template creates a new documentation site in a GitHub repository.
    It fetches a template from the local filesystem, fetches some docs from
    a remote URL, and then publishes the result to a new branch in the
    target repository.
spec:
  owner: team-a
  type: documentation

  parameters:
    - title: Fill in some steps
      required:
        - title
        - branchName
        - targetBranchName
        - targetPath
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]
        title:
          title: Title
          type: string
          description: Title of the pull request
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: This is a description of the pull request
        branchName:
          title: Branch Name
          type: string
          description: Name of the branch to create
          ui:placeholder: create-${{ parameters.name }}
        targetBranchName:
          title: Target Branch Name
          type: string
          description: Name of the branch to create the pull request against
          default: main
        targetPath:
          title: Target Path in repo
          type: string
          description: Name of the directory to create in the repository
          ui:placeholder: docs

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com
            allowedOwners:
              - echohello-dev
            allowedOrganizations:
              - echohello-dev
            allowedRepositories:
              - example

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: 'Create new project: ${{ parameters.name }}'
        branchName: create-${{ parameters.name }}
        description: |
          # New project: ${{ parameters.name }}

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.name }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '${{ parameters.targetPath if parameters.targetPath else parameters.name }}/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: More information
        content: |
          **Entity URL:** `${{ steps['publish'].output.remoteUrl }}`
