apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backstage-tls
spec:
  secretName: backstage-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - '{{ .Values.host }}'
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
