apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backstage
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backstage
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        # Percent of pods to add in each step
        - type: Percent
          value: 100
          periodSeconds: 15

        # Number of pods to add in each step
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
