apiVersion: v1
kind: Secret
metadata:
  name: backstage
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"ghcr.io":{"auth":"{{ (printf "%s:%s" "username" $.Values.githubToken) | b64enc }}"}}}

---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-env-vars
type: Opaque
stringData:
{{- toYaml .Values.secretEnv | nindent 2}}

---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-saml-cert
type: Opaque
stringData:
  cert.pem: |-
    {{ .Values.auth.saml.cert | nindent 6 }}
