apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: customer-experience
  description: Focuses on all aspects of customer interaction with our digital banking services
spec:
  owner: group:ux-design-team