apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-docs
  title: GitHub Docs Template
  tags:
    - recommended
  description: |
    This template creates a new documentation site in a GitHub repository.
    It fetches a template from the local filesystem, fetches some docs from
    a remote URL, and then publishes the result to a new branch in the
    target repository.
spec:
  owner: team-b
  type: documentation

  parameters:
    - title: Fill in some steps
      properties:
        description:
          title: Description
          type: string
          description: Description of the component
          ui:placeholder: A short description of the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: [Group, User]

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
            allowedHosts:
              - github.com
            allowedOwners:
              - echohello-dev
            allowedOrganizations:
              - echohello-dev

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: More information
        content: |
          **Entity URL:** `${{ steps['publish'].output.remoteUrl }}`
