apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: quantum-computer
  description: D-Wave quantum computer for research and computation
spec:
  type: hardware
  owner: quantum-pioneers
  system: quantum-computing