apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ci-cd-pipeline
  description: Continuous Integration and Deployment pipeline
  tags:
    - jenkins
    - groovy
spec:
  type: service
  lifecycle: production
  owner: devops-shamans
  system: devops-toolchain