apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wormhole-navigator
  description: Calculates optimal wormhole routes for package delivery
  tags:
    - rust
    - space
spec:
  type: service
  lifecycle: production
  owner: space-logistics-team
  system: galactic-delivery