apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: docs-template-gitlab
  title: Documentation Template in GitLab
  description: |
    This template creates a new documentation site in a GitLab repository.
spec:
  owner: team-c
  type: documentation

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        targetPath: ${{ parameters.targetPath }}
        values:
          name: ${{ parameters.name }}
          owner: ${{ spec.owner }}

    - id: publish
      name: Publish to GitLab
      action: publish:gitlab
      input:
        repoUrl: gitlab.com?repo=${{ parameters.name }}&owner=echohello
        branchName: ${{ parameters.branchName }}
        description: This is the ${{ parameters.name }} component

  output:
    links:
      - url: ${{ steps.publish.output.url }}
        title: Go to the repository
