#!/usr/bin/env bash
set -euo pipefail

echo "Plausible is running at http://localhost:8000 or http://plausible.localhost"
echo "Backstage is running at http://localhost:7007 or http://backstage.localhost"
echo "Traefik is running at http://localhost:8080 or http://traefik.localhost"
docker compose -f compose.yaml -f compose.plausible.yaml up -d