#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
VERSION=$(./scripts/version)

if [ "${CI:-false}" = "true" ]; then
  git config --global user.email "actions@github.com"
  git config --global user.name "GitHub Actions"
fi

git tag -a "${VERSION}" -m "Release ${VERSION}"
git push origin "${VERSION}"
gh release create "${VERSION}" \
  --title "${VERSION}" \
  --generate-notes \
  --target main
