#!/usr/bin/env bash
set -euo pipefail

echo "Backstage is running at http://localhost:7007 or http://backstage.localhost"
echo "Traefik is running at http://localhost:8080 or http://traefik.localhost"
docker compose up -d