apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: data-analytics-platform-api
  description: API for accessing and managing the data analytics platform
  tags:
    - analytics
    - big-data
spec:
  type: graphql
  lifecycle: production
  owner: data-wizards
  system: data-analytics-platform
  definition: |
    type Query {
      runAnalysis(input: AnalysisInput!): AnalysisResult
      getDatasetInfo(id: ID!): Dataset
    }

    input AnalysisInput {
      datasetId: ID!
      analysisType: AnalysisType!
      parameters: JSON
    }

    type AnalysisResult {
      id: ID!
      status: AnalysisStatus!
      result: JSON
    }

    type Dataset {
      id: ID!
      name: String!
      description: String
      lastUpdated: String
    }

    enum AnalysisType {
      DESCRIPTIVE
      PREDICTIVE
      PRESCRIPTIVE
    }

    enum AnalysisStatus {
      PENDING
      RUNNING
      COMPLETED
      FAILED
    }

    scalar JSON