apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: legacy-cobol-integration-api
  description: API for integrating with legacy COBOL systems
  tags:
    - legacy
    - cobol
    - integration
spec:
  type: openapi
  lifecycle: production
  owner: backend-wizards
  system: core-banking
  definition: |
    openapi: 3.0.0
    info:
      title: Legacy COBOL Integration API
      version: 1.0.0
      description: API for integrating with legacy COBOL systems
    paths:
      /legacy-cobol:
        get:
          summary: Get legacy COBOL data
          responses:
            '200':
              description: A list of legacy COBOL data
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        data:
                          type: string
                        timestamp:
                          type: string
                          format: date-time
                
            '500':
              description: Internal server error
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
                      error_description:
                        type: string

