apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: real-time-transactions-api
  description: API for real-time transaction updates
spec:
  type: asyncapi
  lifecycle: production
  owner: group:backend-services-team
  system: digital-banking-platform
  definition: |
    asyncapi: 2.0.0
    info:
      title: Real-time Transactions API
      version: 1.0.0
    channels:
      transactions/updates:
        publish:
          summary: Real-time updates for transactions
          message:
            payload:
              type: object
              properties:
                transactionId:
                  type: string
                amount:
                  type: number
                status:
                  type: string
                  enum: [pending, completed, failed]
                timestamp:
                  type: string
                  format: date-time